// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CapturedFrame {
  final Uint8List pngBytes;
  final int width;
  final int height;
  final int originX;
  final int originY;
  final double scaleFactor;

  const CapturedFrame({
    required this.pngBytes,
    required this.width,
    required this.height,
    required this.originX,
    required this.originY,
    required this.scaleFactor,
  });

  @override
  int get hashCode =>
      pngBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      originX.hashCode ^
      originY.hashCode ^
      scaleFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapturedFrame &&
          runtimeType == other.runtimeType &&
          pngBytes == other.pngBytes &&
          width == other.width &&
          height == other.height &&
          originX == other.originX &&
          originY == other.originY &&
          scaleFactor == other.scaleFactor;
}

class PlatformCapabilities {
  final String platform;
  final bool desktopCapture;
  final bool regionOverlay;
  final bool globalHotkey;
  final bool pinWindow;

  const PlatformCapabilities({
    required this.platform,
    required this.desktopCapture,
    required this.regionOverlay,
    required this.globalHotkey,
    required this.pinWindow,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      desktopCapture.hashCode ^
      regionOverlay.hashCode ^
      globalHotkey.hashCode ^
      pinWindow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformCapabilities &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          desktopCapture == other.desktopCapture &&
          regionOverlay == other.regionOverlay &&
          globalHotkey == other.globalHotkey &&
          pinWindow == other.pinWindow;
}
