// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A frozen raster plus the metadata needed to place it on the desktop.
///
/// `scale_factor` belongs to the display that owns most of the frame (see
/// [`dominant_scale_factor`]); `displays` lists every display so the UI can
/// resolve the scale under any point of a multi-monitor capture.
class CapturedFrame {
  final Uint8List pngBytes;
  final int width;
  final int height;
  final int originX;
  final int originY;
  final double scaleFactor;
  final List<DisplayInfo> displays;

  const CapturedFrame({
    required this.pngBytes,
    required this.width,
    required this.height,
    required this.originX,
    required this.originY,
    required this.scaleFactor,
    required this.displays,
  });

  @override
  int get hashCode =>
      pngBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      originX.hashCode ^
      originY.hashCode ^
      scaleFactor.hashCode ^
      displays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapturedFrame &&
          runtimeType == other.runtimeType &&
          pngBytes == other.pngBytes &&
          width == other.width &&
          height == other.height &&
          originX == other.originX &&
          originY == other.originY &&
          scaleFactor == other.scaleFactor &&
          displays == other.displays;
}

/// One physical display, in virtual-desktop pixels.
///
/// `scale_factor` is the display's effective DPI divided by 96, so a 200%
/// monitor reports 2.0. Every geometry value stays physical; the UI divides by
/// the scale only when the user asks for logical units.
class DisplayInfo {
  final String id;
  final String name;
  final int originX;
  final int originY;
  final int width;
  final int height;
  final double scaleFactor;
  final bool isPrimary;

  const DisplayInfo({
    required this.id,
    required this.name,
    required this.originX,
    required this.originY,
    required this.width,
    required this.height,
    required this.scaleFactor,
    required this.isPrimary,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      originX.hashCode ^
      originY.hashCode ^
      width.hashCode ^
      height.hashCode ^
      scaleFactor.hashCode ^
      isPrimary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          originX == other.originX &&
          originY == other.originY &&
          width == other.width &&
          height == other.height &&
          scaleFactor == other.scaleFactor &&
          isPrimary == other.isPrimary;
}

class PlatformCapabilities {
  final String platform;
  final bool desktopCapture;
  final bool regionOverlay;
  final bool globalHotkey;
  final bool pinWindow;

  const PlatformCapabilities({
    required this.platform,
    required this.desktopCapture,
    required this.regionOverlay,
    required this.globalHotkey,
    required this.pinWindow,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      desktopCapture.hashCode ^
      regionOverlay.hashCode ^
      globalHotkey.hashCode ^
      pinWindow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformCapabilities &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          desktopCapture == other.desktopCapture &&
          regionOverlay == other.regionOverlay &&
          globalHotkey == other.globalHotkey &&
          pinWindow == other.pinWindow;
}
