// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../capture.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

PlatformCapabilities capabilities() =>
    RustLib.instance.api.crateApiSimpleCapabilities();

Future<CapturedFrame> captureDesktop() =>
    RustLib.instance.api.crateApiSimpleCaptureDesktop();

Future<CapturedFrame> cropFrame({
  required CapturedFrame frame,
  required int left,
  required int top,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleCropFrame(
  frame: frame,
  left: left,
  top: top,
  width: width,
  height: height,
);

Future<String> savePng({required List<int> pngBytes}) =>
    RustLib.instance.api.crateApiSimpleSavePng(pngBytes: pngBytes);

Future<String?> savePngAs({required List<int> pngBytes}) =>
    RustLib.instance.api.crateApiSimpleSavePngAs(pngBytes: pngBytes);
